version: "3.8"

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.file=true"
      - "--providers.file.filename=/etc/traefik/traefik.yml"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "9999:8080"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - app-network

networks:
  app-network:
    external: true
