api:
  insecure: true
  dashboard: true

http:
  routers:
    app:
      rule: Host(`voice-bot-ws.knmholdings.org`)
      service: app
      entryPoints:
        - web

  services:
    app:
      loadBalancer:
        servers:
          - url: http://nginx:80
